import type { BlogPost } from '../domain/blog-post'

export const blogPosts: BlogPost[] = [
  {
    slug: 'frontend-architecture-decisions-nuxt-4',
    title: 'Frontend architecture decisions that survive product evolution',
    titleEs: 'Decisiones de arquitectura frontend que resisten la evolución del producto',
    excerpt: 'How to design Nuxt 4 component systems that stay maintainable as the product grows, the team scales and requirements shift. Real patterns from real migrations.',
    excerptEs: 'Cómo diseñar sistemas de componentes en Nuxt 4 que sigan siendo fáciles de mantener cuando crecen el producto y el equipo y cambian los requisitos. Patrones probados durante migraciones.',
    date: '2026-07-02',
    readTime: '8 min',
    tags: ['Architecture', 'Nuxt', 'Vue', 'TypeScript'],
    tagsEs: ['Arquitectura', 'Nuxt', 'Vue', 'TypeScript'],
    content: [
      "When you start a greenfield project, every architectural decision feels reversible. You pick Vue 3, add Nuxt on top, wire up Tailwind, and ship. Clean, fast, satisfying.",
      "",
      "But six months later — after two pivots, a growing team, and a backlog of edge cases — those early decisions become load-bearing walls. Changing them costs weeks. Ignoring them costs trust.",
      "",
      "**This article is about the decisions that matter.** Not the ones that make you feel clever on day one, but the ones that still feel right on month twelve.",
      "",
      "## Layering your composables",
      "",
      "The `composables/` directory in Nuxt has a habit of becoming a junk drawer. One day you have a clean `useAuth.ts` and `useApi.ts`. Six sprints later you have `useAuth.ts`, `useAuthV2.ts`, `useAuthLegacy.ts`, `useAuthWithRefreshToken.ts`, and a `utils/auth-helpers.ts` that imports from three of them.",
      "",
      "The fix is intentional layering:",
      "",
      "```ts",
      "// composables/core/useAuth.ts — the public API",
      "// composables/core/internal/useTokenManager.ts — implementation detail",
      "// composables/core/internal/useSessionStore.ts — state management",
      "```",
      "",
      "The internal folder convention signals to the team: \"import from here at your own risk.\" It won't stop anyone determined, but it sets a clear boundary. And in architecture, clear boundaries are half the battle.",
      "",
      "## Component contracts, not props drilling",
      "",
      "Props can document a component, but that documentation stops helping when nobody can make sense of it — especially when `UserCard` accepts fourteen props and three are only used in one edge case.",
      "",
      "Instead of a flat prop list, group related concerns:",
      "",
      "```vue",
      "<script setup lang=\"ts\">",
      "interface UserCardProps {",
      "  user: { name: string; avatar: string }",
      "  permissions?: { canEdit: boolean; canDelete: boolean }",
      "  theme?: 'light' | 'dark' | 'system'",
      "}",
      "</script>",
      "```",
      "",
      "This is a contract. When a new developer opens the file, they see exactly what the component needs — not a wall of individual props that might or might not be related.",
      "",
      "## Migration strategies that don't freeze the team",
      "",
      "Migrations are not optional. Vue 2 to 3, Nuxt 2 to 4, Options API to Composition API — these are the kind of work that product managers hate scheduling and engineers dread executing.",
      "",
      "The pattern that works: **strangler fig with parallel routing.**",
      "",
      "Run both apps side by side. Route new pages to Nuxt 4. Keep legacy routes on Nuxt 2. Use a reverse proxy to stitch them together. Migrate page by page, not all at once.",
      "",
      "This costs more infrastructure upfront but saves months of blocked deployments and the morale hit of a \"big bang\" migration gone wrong.",
      "",
      "---",
      "",
      "Architecture isn't about picking the right library. It's about making decisions that give your future self options. The best architecture decision is the one you don't have to undo."
    ].join('\n'),
    contentEs: [
      "Al empezar un proyecto desde cero, cada decisión arquitectónica parece reversible. Eliges Vue 3, añades Nuxt, configuras Tailwind y publicas. Todo encaja; el resultado es rápido y satisfactorio.",
      "",
      "Pero seis meses después —tras un par de cambios de rumbo, un equipo más grande y nuevos casos límite— esas primeras decisiones ya sostienen partes importantes del sistema. Cambiarlas cuesta semanas; ignorarlas, la confianza del equipo.",
      "",
      "**Este artículo trata de las decisiones que importan:** las que siguen teniendo sentido un año después, no solo las que parecen brillantes el primer día.",
      "",
      "## Organizar los composables por capas",
      "",
      "En Nuxt, el directorio `composables/` puede acabar convertido en un cajón de sastre. Al principio tienes `useAuth.ts` y `useApi.ts`; seis sprints después, también `useAuthV2.ts`, `useAuthLegacy.ts`, `useAuthWithRefreshToken.ts` y un `utils/auth-helpers.ts` que importa de varios.",
      "",
      "La solución es organizar por capas de forma intencionada:",
      "",
      "```ts",
      "// composables/core/useAuth.ts — la API pública",
      "// composables/core/internal/useTokenManager.ts — detalle de implementación",
      "// composables/core/internal/useSessionStore.ts — gestión de estado",
      "```",
      "",
      "Llamar `internal` a esa carpeta indica al equipo que esos módulos son detalles de implementación. No impedirá que alguien los importe, pero deja claro dónde está el límite. En arquitectura, establecer límites claros ya es una parte importante del trabajo.",
      "",
      "## Contratos de componentes, no props planas",
      "",
      "Las props también documentan un componente, pero esa documentación deja de ayudar cuando nadie la entiende; por ejemplo, si `UserCard` acepta catorce props y tres solo se usan en un caso muy concreto.",
      "",
      "En vez de una lista extensa, agrupa las propiedades que representan conceptos relacionados:",
      "",
      "```vue",
      "<script setup lang=\"ts\">",
      "interface UserCardProps {",
      "  user: { name: string; avatar: string }",
      "  permissions?: { canEdit: boolean; canDelete: boolean }",
      "  theme?: 'light' | 'dark' | 'system'",
      "}",
      "</script>",
      "```",
      "",
      "Este contrato permite que quien abra el archivo entienda qué necesita el componente, sin tener que descifrar una lista de props que quizá no guarden relación entre sí.",
      "",
      "## Estrategias de migración que no congelan al equipo",
      "",
      "Las migraciones llegan tarde o temprano: de Vue 2 a 3, de Nuxt 2 a 4 o de Options API a Composition API. A los equipos de producto les cuesta encontrarles hueco en el calendario y los equipos de ingeniería saben el trabajo que implican.",
      "",
      "Una estrategia útil es el patrón **Strangler Fig con enrutamiento en paralelo.**",
      "",
      "Mantén ambas aplicaciones en marcha: dirige las páginas nuevas a Nuxt 4 y conserva las rutas existentes en Nuxt 2. Un proxy inverso puede unirlas mientras migras página a página.",
      "",
      "Requiere más infraestructura al principio, pero evita meses de despliegues bloqueados y reduce el impacto de intentar migrarlo todo de una vez.",
      "",
      "---",
      "",
      "La arquitectura no consiste en elegir la librería perfecta, sino en tomar decisiones que dejen margen para el futuro. Una buena decisión es aquella que no necesitas deshacer."
    ].join('\n'),
    published: true,
  },
  {
    slug: 'self-hosted-ocr-pipeline-docker',
    title: 'Building a self-hosted OCR pipeline with Docker, Traefik and fallback strategies',
    titleEs: 'Construyendo un pipeline OCR self-hosted con Docker, Traefik y estrategias de fallback',
    excerpt: 'A production-ready OCR ingestion stack designed for resilience. Multi-engine routing, automatic fallback, and monitoring that tells you when documents need human attention.',
    excerptEs: 'Un stack de ingesta OCR listo para producción diseñado para resiliencia. Enrutamiento multi-motor, fallback automático y monitorización que avisa cuando los documentos necesitan atención humana.',
    date: '2026-06-18',
    readTime: '12 min',
    tags: ['Docker', 'OCR', 'Self-hosting', 'Automation'],
    content: 'Full OCR pipeline article content...',
    contentEs: 'Contenido completo del artículo del pipeline OCR...',
    published: false,
  },
  {
    slug: 'typescript-patterns-vue-composables',
    title: 'TypeScript patterns that make Vue composables feel like a typed API',
    titleEs: 'Patrones de TypeScript que hacen que los composables de Vue parezcan una API tipada',
    excerpt: 'Moving beyond basic ref typing to composables that enforce invariants at the type level, prevent impossible states, and give your IDE real superpowers.',
    excerptEs: 'Más allá del tipado básico de refs hacia composables que imponen invariantes a nivel de tipos, previenen estados imposibles y le dan superpoderes reales a tu IDE.',
    date: '2026-05-30',
    readTime: '10 min',
    tags: ['TypeScript', 'Vue', 'Patterns', 'DX'],
    content: 'Full TypeScript patterns article content...',
    contentEs: 'Contenido completo del artículo de patrones TypeScript...',
    published: false,
  },
  {
    slug: 'homelab-monitoring-grafana-prometheus',
    title: "Homelab monitoring that doesn't wake you up at 3am",
    titleEs: 'Monitorización de homelab que no te despierta a las 3am',
    excerpt: 'Setting up Grafana, Prometheus and Alertmanager for a self-hosted stack. The goal: alerts that are actionable, dashboards that are readable, and silence when everything is fine.',
    excerptEs: 'Configurando Grafana, Prometheus y Alertmanager para un stack self-hosted. El objetivo: alertas accionables, dashboards legibles y silencio cuando todo va bien.',
    date: '2026-05-12',
    readTime: '7 min',
    tags: ['Homelab', 'Monitoring', 'Docker', 'DevOps'],
    content: 'Full monitoring article content...',
    contentEs: 'Contenido completo del artículo de monitorización...',
    published: false,
  },
]

export function getAllBlogPosts(): BlogPost[] {
  return blogPosts.filter(post => post.published !== false)
}

export function getBlogPostBySlug(slug: string): BlogPost | undefined {
  return blogPosts.find(post => post.slug === slug && post.published !== false)
}
