import type { BlogPost } from '../domain/blog-post'

export const blogPosts: BlogPost[] = [
  {
    slug: 'frontend-architecture-decisions-nuxt-4',
    title: 'Frontend architecture decisions that survive product evolution',
    titleEs: 'Decisiones de arquitectura frontend que sobreviven a la evolución del producto',
    excerpt: 'How to design Nuxt 4 component systems that stay maintainable as the product grows, the team scales and requirements shift. Real patterns from real migrations.',
    excerptEs: 'Cómo diseñar sistemas de componentes en Nuxt 4 que se mantienen mantenibles cuando el producto crece, el equipo escala y los requisitos cambian. Patrones reales de migraciones reales.',
    date: '2026-07-02',
    readTime: '8 min',
    tags: ['Architecture', 'Nuxt', 'Vue', 'TypeScript'],
    content: [
      "When you start a greenfield project, every architectural decision feels reversible. You pick Vue 3, add Nuxt on top, wire up Tailwind, and ship. Clean, fast, satisfying.",
      "",
      "But six months later — after two pivots, a growing team, and a backlog of edge cases — those early decisions become load-bearing walls. Changing them costs weeks. Ignoring them costs trust.",
      "",
      "**This article is about the decisions that matter.** Not the ones that make you feel clever on day one, but the ones that still feel right on month twelve.",
      "",
      "## Layering your composables",
      "",
      "The `composables/` directory in Nuxt has a habit of becoming a junk drawer. One day you have a clean `useAuth.ts` and `useApi.ts`. Six sprints later you have `useAuth.ts`, `useAuthV2.ts`, `useAuthLegacy.ts`, `useAuthWithRefreshToken.ts`, and a `utils/auth-helpers.ts` that imports from three of them.",
      "",
      "The fix is intentional layering:",
      "",
      "```ts",
      "// composables/core/useAuth.ts — the public API",
      "// composables/core/internal/useTokenManager.ts — implementation detail",
      "// composables/core/internal/useSessionStore.ts — state management",
      "```",
      "",
      "The internal folder convention signals to the team: \"import from here at your own risk.\" It won't stop anyone determined, but it sets a clear boundary. And in architecture, clear boundaries are half the battle.",
      "",
      "## Component contracts, not props drilling",
      "",
      "Props are documentation. But documentation that nobody reads — especially when your `UserCard` accepts fourteen props and three of them are only used in one edge-case slot.",
      "",
      "Instead of a flat prop list, group related concerns:",
      "",
      "```vue",
      "<script setup lang=\"ts\">",
      "interface UserCardProps {",
      "  user: { name: string; avatar: string }",
      "  permissions?: { canEdit: boolean; canDelete: boolean }",
      "  theme?: 'light' | 'dark' | 'system'",
      "}",
      "</script>",
      "```",
      "",
      "This is a contract. When a new developer opens the file, they see exactly what the component needs — not a wall of individual props that might or might not be related.",
      "",
      "## Migration strategies that don't freeze the team",
      "",
      "Migrations are not optional. Vue 2 to 3, Nuxt 2 to 4, Options API to Composition API — these are the kind of work that product managers hate scheduling and engineers dread executing.",
      "",
      "The pattern that works: **strangler fig with parallel routing.**",
      "",
      "Run both apps side by side. Route new pages to Nuxt 4. Keep legacy routes on Nuxt 2. Use a reverse proxy to stitch them together. Migrate page by page, not all at once.",
      "",
      "This costs more infrastructure upfront but saves months of blocked deployments and the morale hit of a \"big bang\" migration gone wrong.",
      "",
      "---",
      "",
      "Architecture isn't about picking the right library. It's about making decisions that give your future self options. The best architecture decision is the one you don't have to undo."
    ].join('\n'),
    contentEs: [
      "Cuando empiezas un proyecto nuevo, cada decisión arquitectónica parece reversible. Escoges Vue 3, añades Nuxt, conectas Tailwind y lanzas. Limpio, rápido, satisfactorio.",
      "",
      "Pero seis meses después — tras dos pivotes, un equipo más grande y una acumulación de casos extremos — esas primeras decisiones se convierten en muros de carga. Cambiarlas cuesta semanas. Ignorarlas cuesta confianza.",
      "",
      "**Este artículo trata sobre las decisiones que importan.** No las que te hacen sentir listo el primer día, sino las que siguen sintiéndose acertadas en el mes doce.",
      "",
      "## Organizar los composables por capas",
      "",
      "El directorio `composables/` en Nuxt tiende a convertirse en un cajón de sastre. Un día tienes `useAuth.ts` y `useApi.ts` limpios. Seis sprints después tienes `useAuth.ts`, `useAuthV2.ts`, `useAuthLegacy.ts`, `useAuthWithRefreshToken.ts` y un `utils/auth-helpers.ts` que importa de tres de ellos.",
      "",
      "La solución es organizar por capas de forma intencionada:",
      "",
      "```ts",
      "// composables/core/useAuth.ts — la API pública",
      "// composables/core/internal/useTokenManager.ts — detalle de implementación",
      "// composables/core/internal/useSessionStore.ts — gestión de estado",
      "```",
      "",
      "La convención de carpeta internal le dice al equipo: \"importa desde aquí bajo tu propio riesgo.\" No detendrá a nadie decidido, pero establece un límite claro. Y en arquitectura, los límites claros son la mitad del trabajo.",
      "",
      "## Contratos de componentes, no props planas",
      "",
      "Las props son documentación. Pero documentación que nadie lee — especialmente cuando tu `UserCard` acepta catorce props y tres de ellas solo se usan en un slot de caso extremo.",
      "",
      "En lugar de una lista plana de props, agrupa conceptos relacionados:",
      "",
      "```vue",
      "<script setup lang=\"ts\">",
      "interface UserCardProps {",
      "  user: { name: string; avatar: string }",
      "  permissions?: { canEdit: boolean; canDelete: boolean }",
      "  theme?: 'light' | 'dark' | 'system'",
      "}",
      "</script>",
      "```",
      "",
      "Esto es un contrato. Cuando un nuevo desarrollador abre el archivo, ve exactamente lo que necesita el componente — no una pared de props individuales que pueden o no estar relacionadas.",
      "",
      "## Estrategias de migración que no congelan al equipo",
      "",
      "Las migraciones no son opcionales. Vue 2 a 3, Nuxt 2 a 4, Options API a Composition API — este es el tipo de trabajo que los product managers odian planificar y los ingenieros temen ejecutar.",
      "",
      "El patrón que funciona: **strangler fig con enrutamiento paralelo.**",
      "",
      "Ejecuta ambas aplicaciones lado a lado. Dirige las páginas nuevas a Nuxt 4. Mantén las rutas heredadas en Nuxt 2. Usa un proxy inverso para unirlas. Migra página por página, no todo de golpe.",
      "",
      "Esto cuesta más infraestructura al principio pero ahorra meses de despliegues bloqueados y el golpe anímico de una migración \"big bang\" mal ejecutada.",
      "",
      "---",
      "",
      "La arquitectura no consiste en elegir la librería correcta. Consiste en tomar decisiones que le den opciones a tu yo del futuro. La mejor decisión arquitectónica es la que no tienes que deshacer."
    ].join('\n'),
  },
  {
    slug: 'self-hosted-ocr-pipeline-docker',
    title: 'Building a self-hosted OCR pipeline with Docker, Traefik and fallback strategies',
    titleEs: 'Construyendo un pipeline OCR self-hosted con Docker, Traefik y estrategias de fallback',
    excerpt: 'A production-ready OCR ingestion stack designed for resilience. Multi-engine routing, automatic fallback, and monitoring that tells you when documents need human attention.',
    excerptEs: 'Un stack de ingesta OCR listo para producción diseñado para resiliencia. Enrutamiento multi-motor, fallback automático y monitorización que avisa cuando los documentos necesitan atención humana.',
    date: '2026-06-18',
    readTime: '12 min',
    tags: ['Docker', 'OCR', 'Self-hosting', 'Automation'],
    content: 'Full OCR pipeline article content...',
    contentEs: 'Contenido completo del artículo del pipeline OCR...',
  },
  {
    slug: 'typescript-patterns-vue-composables',
    title: 'TypeScript patterns that make Vue composables feel like a typed API',
    titleEs: 'Patrones de TypeScript que hacen que los composables de Vue parezcan una API tipada',
    excerpt: 'Moving beyond basic ref typing to composables that enforce invariants at the type level, prevent impossible states, and give your IDE real superpowers.',
    excerptEs: 'Más allá del tipado básico de refs hacia composables que imponen invariantes a nivel de tipos, previenen estados imposibles y le dan superpoderes reales a tu IDE.',
    date: '2026-05-30',
    readTime: '10 min',
    tags: ['TypeScript', 'Vue', 'Patterns', 'DX'],
    content: 'Full TypeScript patterns article content...',
    contentEs: 'Contenido completo del artículo de patrones TypeScript...',
  },
  {
    slug: 'homelab-monitoring-grafana-prometheus',
    title: "Homelab monitoring that doesn't wake you up at 3am",
    titleEs: 'Monitorización de homelab que no te despierta a las 3am',
    excerpt: 'Setting up Grafana, Prometheus and Alertmanager for a self-hosted stack. The goal: alerts that are actionable, dashboards that are readable, and silence when everything is fine.',
    excerptEs: 'Configurando Grafana, Prometheus y Alertmanager para un stack self-hosted. El objetivo: alertas accionables, dashboards legibles y silencio cuando todo va bien.',
    date: '2026-05-12',
    readTime: '7 min',
    tags: ['Homelab', 'Monitoring', 'Docker', 'DevOps'],
    content: 'Full monitoring article content...',
    contentEs: 'Contenido completo del artículo de monitorización...',
  },
]

export function getAllBlogPosts(): BlogPost[] {
  return blogPosts
}

export function getBlogPostBySlug(slug: string): BlogPost | undefined {
  return blogPosts.find(post => post.slug === slug)
}
